config/routes.rb
Rails.application.routes.draw do
  resources :quote_forms
  #get 'page/index'
  root 'page#index'
  get  'page/residential'
  get  'page/commercial'
  get  'page/quote'
  get  'quote_forms/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord


end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/quote_form.rb
class QuoteForm < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/get_controller.rb
class GetController < ApplicationController
  def quote
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end

  def residential
  end

  def commercial
  end

  def quote
  end

end

app/controllers/quote_forms_controller.rb
class QuoteFormsController < ApplicationController
  before_action :set_quote_form, only: %i[ show edit update destroy ]

  # GET /quote_forms or /quote_forms.json
  def index
    @quote_forms = QuoteForm.all
  end

  # GET /quote_forms/1 or /quote_forms/1.json
  def show
  end

  # GET /quote_forms/new
  def new
    @quote_form = QuoteForm.new
  end

  # GET /quote_forms/1/edit
  def edit
  end

  # POST /quote_forms or /quote_forms.json
  def create
    @quote_form = QuoteForm.new(quote_form_params)

    respond_to do |format|
      if @quote_form.save
        format.html { redirect_to @quote_form, notice: "Quote form was successfully created." }
        format.json { render :show, status: :created, location: @quote_form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quote_forms/1 or /quote_forms/1.json
  def update
    respond_to do |format|
      if @quote_form.update(quote_form_params)
        format.html { redirect_to @quote_form, notice: "Quote form was successfully updated." }
        format.json { render :show, status: :ok, location: @quote_form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quote_forms/1 or /quote_forms/1.json
  def destroy
    @quote_form.destroy
    respond_to do |format|
      format.html { redirect_to quote_forms_url, notice: "Quote form was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote_form
      @quote_form = QuoteForm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_form_params
      params.require(:quote_form).permit(:FirstName, :LastName, :PhoneNumber, :Email, :Elevators, :Price_Per_Unit, :Sum_For_All_Units, :Installation_Fees, :Total_Price)
    end
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController
  def residential
  end
  def commercial
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drink_helper.rb
module DrinkHelper
  attr_reader :drinks, :drink
end

app/helpers/food_helper.rb
module FoodHelper
  attr_reader :foods, :food
end

app/helpers/get_helper.rb
module GetHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  attr_reader :products, :product
end

app/helpers/quote_forms_helper.rb
module QuoteFormsHelper
  attr_reader :quote_forms, :quote_form
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hello</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script>var plugin_path = '/assets/plugins/';</script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC-Is4GjO_9unj2RTF0MRXI_zGuWV_7UB4&callback=initMap"></script>
    
  </head>

  <body class="smoothscroll enable-animation">
    <%= render 'page/header' %>
    <%= yield %>
    <%= render 'page/footer' %>
  </body>
</html>

app/views/page/_header.html.erb
<div id="header" class="navbar-toggleable-md sticky header-md clearfix">
<!-- TOP NAV -->
    <header id="topNav">
        <div class="container">

            <!-- Mobile Menu Button -->
            <button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
                <i class="fa fa-bars"></i>
            </button>

            <!-- Logo -->
            <a class="logo float-left scrollTo" href="#top">
                <%# <img src="assets/images/RE/RE_Logo.png" alt="RocketElevatorsLogo" /> %>
                <%= image_tag("/assets/RE/RE_Logo.png", class: "logo float-left scrollTo") %>
            </a>

            

            <!---->
            <div class="navbar-collapse collapse float-right nav-main-collapse submenu-dark">
                <nav class="nav-main">

                    <ul id="topMain" class="nav nav-pills nav-main nav-onepage">
                        <li><!-- HOME -->
                        
                            <%= link_to "HOME", root_path %>
                        
                        </li>
                        <li class="nav-item dropdown">
                            <a id="services-nav" class="dropdown-toggle" data-toggle="dropdown" href="#services">
                                SERVICES 
                            </a>
                            <ul class="dropdown-menu">
                                <li class="dropdown-item"><%= link_to "Residential", page_residential_path %></li>
                                <li class="dropdown-item"><%= link_to "Commercial",  page_commercial_path %></li>
                            </ul>
                        </li>
                        <li><!-- WORK -->
                            <%= link_to "PORTFOLIO", "#{root_path}#portfolio" %>
                            </a>
                        </li>
                        <li><!-- NEWS -->
                        <%= link_to "NEWS", "#{root_path}#news" %>
                            </a>
                        </li>
                        <li><!-- CLIENTS -->
                        <%= link_to "CLIENTS", "#{root_path}#clients" %>
                            </a>
                        </li>
                        <li><!-- CONTACT -->
                        <%= link_to "CONTACT", "#{root_path}#contact" %>
                            </a>
                        </li>
                            
                                
                            
                        </li>
                    </ul>

                </nav>
            </div>

        </div>
    </header>
</div>
<!-- /Top Nav -->

app/views/page/commercial.html.erb
<!-- wrapper -->
<div id="wrapper">

	<!-- HOME -->
	<section id="home" style="padding-top: 75px">
				
		<div class="container text-center">
			
			<h1 class="m-0 fs-40 fw-300 wow fadeInUp" data-wow-delay="0.4s">Rocket Elevators can always <span style="font-style:oblique ;color: blue;">Elevate</span> the limits higher</h1>
			<p class="lead font-lato fs-20 wow fadeInUp" data-wow-delay="0.7s">Even the biggest projects fail to make us dizzy!</p>
			
			<div class="mt-30 mb-10">
					<p style="font-weight: 400;font-size: 16px;">With almost 50 years of experiences, we did a lot of projects recognized for being almost impossible to accomplish.<br>
				On the worksites, our dedicated crew, with the support from our engineering team, can realized exeptional things within the limits of possible</p>
				<hr>   
				<%= link_to "PRINCING", "/quote_forms/new", class: "btn btn-3d btn-danger" %>
				<hr>
				<a href="#testimonials" style="font-weight: 500;font-size: 15px;color: lime;">View our partners testimonials</a>
			</div>



			<div class="row mt-100 text-center">

				<div class="col-lg-6 mt-30 mb-5">
					<%= image_tag("/assets/RE/Commercial/1200x800/Aston-MartinApp_1200x800.jpg",class:"img-fluid", width:"500", height:"300", alt:"product line")%> 
					<%= image_tag("/assets/RE/Portfolio/OWTC_1200x800.jpg",class:"img-fluid", width:"500", height:"300", alt:"product line")%>
				</div>
				<div class="col-lg-6 mt-30 mb-5">
					<%= image_tag("/assets/RE/Commercial/1200x800/2998_1200x800.jpg",class:"img-fluid", width:"500", height:"300", alt:"product line")%> 
					<%= image_tag("/assets/RE/Commercial/1200x800/Toronto_1200x800.jpg",class:"img-fluid", width:"500", height:"300", alt:"product line")%>
				</div>

			</div>


		</div>
		<div class="mt-80 text-center">
				
		<%= image_tag("/assets/RE/Commercial/Porsche-Design-Tower_Automobile-Lift-System.jpg",class:"img-fluid", width:"1000", height:"400", alt:"product line")%>
				
	</div>    

	</section>
	<!-- /HOME -->

	<!-- PRICING -->
	<a id="pricing"></a>
	<hr>
	<section id="pricing" style="padding-top: 10px">
		<div class="container">

			<header class="text-center mt-20 mb-60">
				<h2>Our Pricing</h2>
				<p class="lead font-lato">Choose the desired option to start a quote</p>
				<hr />
			</header>

			<div class="row">

				<div class="col-md-4 col-sm-3">
					
					<div class="price-clean price-clean-popular"> 
						<div class="ribbon"> 
							<div class="ribbon-inner">Standard</div>
						</div>                               
						<h4>
							<sup>$</sup>7,565
						</h4>
						<h5> Starting at *</h5>
						<hr />
						<p style="font-size:14px; color:gold">For individuals looking for something affordable</p>
						<hr />
						<%= link_to "Get Quote", "/quote_forms/new", class: "btn btn-3d btn-danger" %>
					</div>
				
				</div>
				
				<div class="col-md-4 col-sm-3">
					
					<div class="price-clean price-clean-popular"> 
						<div class="ribbon"> 
							<div class="ribbon-inner">Premium</div>
						</div>                               
						<h4>
							<sup>$</sup>12,345
						</h4>
						<h5> Starting at *</h5>
						<hr />
						<p style="font-size:14px; color:gold">For more ambitious projects</p>
						<hr />
						<%= link_to "Get Quote", "/quote_forms/new", class: "btn btn-3d btn-danger" %>
					</div>
				
				</div>

				<div class="col-md-4 col-sm-3">
					
					<div class="price-clean price-clean-popular"> 
						<div class="ribbon"> 
							<div class="ribbon-inner">Excelium</div>
						</div>
						
						<h4>
							<sup>$</sup>15,400
						</h4>
						<h5> Starting at *</h5>
						<hr/>
						<p style="font-size:14px; color:gold">When your serious about luxury...</p>
						<hr/>
						<%= link_to "Get Quote", "/quote_forms_new", class: "btn btn-3d btn-danger" %>
					</div>
					
				</div>
				
			</div>
			<div>
			<p class="pt-20 text-center h-10" style="font-style: italic;">*More information may be required to complete the quote request</p>
			</div>
		</div>
	</section>
	<!-- /PRICING -->



	<!-- TESTIMONIALS -->
	<section id="testimonials" class="alternate">
		<div class="container">

			<header class="text-center mt-40">
				<h2>Testimonials</h2>
				<p class="lead font-lato">See how we have change their live...</p>
				<hr />
			</header>

			<!-- 
				Note: remove class="rounded" from the img for squared image!
			-->
			<div class="row mb-60">
				<div class="col-md-4">
					<div class="testimonial testimonial-bordered p-15">
						<figure class="float-left">
							<%= image_tag("/assets/RE/Commercial/Testimonial/T-M_sm.jpg",class:"rounded", width:"100", height:"100", alt:"testimonial")%>
						</figure>
						<div class="testimonial-content">
							<p>"Would have been impossible to build the Porsche Tower without the expertise of Rocket Elevators"</p>
							<cite>
								T. Murphy
								<span>Coastal Construction, Founder & CEO</span>
							</cite>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="testimonial testimonial-bordered p-15">
						<figure class="float-left">
							<%= image_tag("/assets/RE/Commercial/Testimonial/B-B_sm.jpg",class:"rounded", width:"100", height:"100", alt:"testimonial")%>
						</figure>
						<div class="testimonial-content">
							<p>"A great team to work with.We are partner with Rocket Elevators since the mid 80's and doesn't plan to stop"</p>
							<cite>
								B. Bechtel
								<span>Bechtel Groups CEO</span>
							</cite>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="testimonial testimonial-bordered p-15">
						<figure class="float-left">
							<%= image_tag("/assets/RE/Residential page/Donald_trump_300x300.png",class:"rounded", width:"100", height:"100", alt:"testimonial image")%>
						</figure>
						<div class="testimonial-content">
							<p>"They have done a great job in my Trump Tower.If someone tell you bad things about them, it's FAKE news!!"</p>
							<cite>
								Donald Gump
								<span>The Trump Organization, Founder & Owner</span>
							</cite>
						</div>
					</div>
				</div>
			</div>

		</div>
	</section>
	<!-- /TESTIMONIALS -->
</div>

app/views/quote_forms/edit.html.erb
<h1>Editing Quote Form</h1>

<%= render 'form', quote_form: @quote_form %>

<%= link_to 'Show', @quote_form %> |
<%= link_to 'Back', quote_forms_path %>

app/views/quote_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quote Forms</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Phonenumber</th>
      <th>Email</th>
      <th>Elevators</th>
      <th>Price Per Unit</th>
      <th>Sum For All Units</th>
      <th>Installation Fees</th>
      <th>Total Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quote_forms.each do |quote_form| %>
      <tr>
        <td><%= quote_form.FirstName %></td>
        <td><%= quote_form.LastName %></td>
        <td><%= quote_form.PhoneNumber %></td>
        <td><%= quote_form.Email %></td>
        <td><%= quote_form.Elevators %></td>
        <td><%= quote_form.Price_Per_Unit %></td>
        <td><%= quote_form.Sum_For_All_Units %></td>
        <td><%= quote_form.Installation_Fees %></td>
        <td><%= quote_form.Total_Price %></td>
        <td><%= link_to 'Show', quote_form %></td>
        <td><%= link_to 'Edit', edit_quote_form_path(quote_form) %></td>
        <td><%= link_to 'Destroy', quote_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote Form', new_quote_form_path %>

app/views/quote_forms/new.html.erb
<<!-- wrapper -->
<div id="wrapper">

	<!-- -->
	<section id="slider" class="halfheight mobile-fullheight" style="background:url('assets/images/RE/Parallax_bg.jpg') top;">
	<%= image_tag("/assets/RE/Parallax_bg.jpg",class:"img-fluid", width:"1500", height:"300", alt:"product line")%>

		<span class="raster overlay dark-3 z-index-0"><!-- dark|light overlay [0 to 9 opacity] --></span>

	</section>
	<!-- / -->


	<div id="quoteform" class="row justify-content-center" style="background-color:#313131">
			<div class="col-md">

				<header class="text-center">
					<h1 class="fs-50 mt-20 mb-0">CHECK YOUR PRICE</h1>
					<p class="fw-300">LET THE JOURNEY TO YOUR NEW ELEVATOR BEGIN</p>
				</header>

			</div>

	</div>

	<div class="row " style="background-image:-webkit-linear-gradient(left,#3072e0,#9e040a,white);height: 8px;">
		<hr class="mt-0">
	</div>

		<!-- ******************* CENTRALE SECTION **************************-->

	<form id="" autocomplete="off">
		<div id="inputs" class="container">
			<div class="row pt-50">	
				<div class="col-md-4 col-xs-12" style="justify-content:right">
					<label class="txtst24 pr-30 d-inline">Building Type</label>
					
					<select id="building-type" class="form-control-pointer stxtst18" name="building-types">
							<option id="choose" class ="txtst18" value="choose">Choose one type</option>
							<option id="residential" class="txtst18" value="residential">Residential</option>
							<option id="commercial" class="txtst18" value="commercial">Commercial</option>
							<option id="corporate" class="txtst18" value="corporate">Corporate</option>
							<option id="hybrid" class="txtst18" value="hybrid">Hybrid</option>
					</select>
				</div>	

			</div>			
					
				<!-- ************************* RESIDENTIAL FORM ******************************* -->
	
			<div class="row">

				<div id="number-of-apartments" class="col-md-4 col-xs-12 pt-30 resid">
					<label for="res-aparts" style="font-size: 18px;">Total No. of Apts</label>
					<input id="res-apts" class="form-control go" onkeyup="finalprice();" oninput=" validity.valid||(value='');" placeholder="# of apartments" name="res-aparts" type="number" min="0" value="0">

				</div>
				<div id="number-of-floors" class="col-md-4 col-xs-12 pt-30">
					<label for="res-floors" style="font-size: 18px;">No. of Floors</label>
					<input id="floors" class="form-control go" onkeyup="finalprice();" oninput=" validity.valid||(value='');" placeholder="# of floors" name="res-floors" type="number" min="0" value="0">
				</div>
				<div id="number-of-basements" class="col-md-4 col-xs-12 pt-30">
					<label for="res-basements" style="font-size: 18px;">No. of Basements</label>
					<input id="basements" class="form-control go" onkeyup="finalprice();" oninput=" validity.valid||(value='');" placeholder="# of basements" name="res-basements" type="number" min="0" value="0">
				</div>  
	
			
				<!-- ************************* COMMERCIAL FORM ******************************* -->

			
				<div id="number-of-compagnies" class="col-md-4 col-xs-12 pt-30 comm">
					<label style="font-size: 18px;">No. of Distinct Bus.</label>
					<input class="form-control go" oninput="validity.valid||(value='');" placeholder="# of distinct business" name="comm-distinctbus" type="number" min="0" value="0">
				</div>

				<div id="number-of-parking-spots" class="col-md-4 col-xs-12 pt-30 commcorphyb">
					<label style="font-size: 18px;">No. of Parking</label>
					<input class="form-control go" oninput="validity.valid||(value='');" placeholder="# of parkings" name="comm-parking" type="number" min="0" value="0">

				</div>
				<div id="number-of-elevators" class="col-md-4 col-xs-12 pt-30 comm">
					<label style="font-size: 18px;">No. of Elevator Needed</label>
					<input id="elev-needed" class="form-control go" onkeyup="finalprice();" oninput=" validity.valid||(value='');" placeholder="# of elevator needed" name="comm-elevators" type="number" min="0" value="0">
				</div> 

				<!-- ************************* CORPORATE FORM ******************************* -->


				<div id="number-of-corporations" class="col-md-4 col-xs-12 pt-30 corp">
					<label style="font-size: 18px;">No. of Separate Tennant</label>
					<input class="form-control go" oninput="validity.valid||(value='');" placeholder="# of tennant company" name="corp-tennant" type="number" min="0" value="0">
				</div>
				<div id="maximum-occupancy" class="col-md-4 col-xs-12 pt-30 corphyb">
					<label style="font-size: 18px;">No. of Occupant/Floor</label>
					<input id="occ-flr" class="form-control go" onkeyup="finalprice();" oninput=" validity.valid||(value='');" placeholder="# of occ/floors" name="corp-occupants" type="number" min="0" value="0">
				</div> 
				<!-- ************************* HYBRID FORM ******************************* -->


				<div id="number-of-compagnies" class="col-md-4 col-xs-12 pt-30 hybr">
					<label style="font-size: 18px;">No. of Distinct Bus.</label>
					<input class="form-control go" oninput="validity.valid||(value='');" placeholder="# of tennants" name="hyb-business" type="number" min="0" value="0">
				</div>

				<div id="business-hours" class="col-md-4 col-xs-12 pt-30 hybr">
					<label style="font-size: 18px;">Hr of Activity/Day</label>
					<input class="form-control go" oninput="validity.valid||(value='');" placeholder="Hr/day maximum 24" name="hyb-activday" type="number" min="1" max="24" value="0">
				</div> 
						
			</div>

		</div>

	</form>
				<!-- ************************ PRODUCT LINES SECTION ***************************-->


	<div class="row mt-50" style="background-image:-webkit-linear-gradient(left,white,#3072e0,#9e040a);height: 4px;">
		<hr class="mt-0">
	</div>

	<div id="productline" class="col mt-10">

		<div class="row row-sm-12" style="justify-content:center">
			<!-- <div class="col col-xs-12"></div> -->
			<div class="col-md-2 col-xs-12" style="justify-content:center">
				<a class="txtst24">
					Product line:
				</a>
			</div>
			<div class="col-md-1 col-sm-12 pt-5" style="justify-content:center">
				<input onclick="finalprice()" class="form-check-input" type="radio" name="product-line" id="standard" value="standard" checked>
				<label class="form-check-label d-inline" style="font-size:18px" for="res-step-1">
					Standard
				</label>
			</div>
			<div class="col-md-1 col-xs-12 pt-5" style="justify-content:center">
				<input onclick="finalprice()" class="form-check-input" type="radio" name="product-line" id="premium" value="premium">
				<label class="form-check-label d-inline" style="font-size:18px" for="com-step-1">
					Premium
				</label>
			</div>
			<div class="col-md-1 col-xs-12 pt-5" style="justify-content:center">
				<input onclick="finalprice()" class="form-check-input" type="radio" name="product-line" id="excelium" value="excelium">
				<label class="form-check-label d-inline" style="font-size:18px" for="cor-step-1">
					Excelium
				</label>
			</div>

		</div>	
	</div>

	<div class="row mt-10" style="background-image:-webkit-linear-gradient(left,#9e040a,white,#3072e0);height: 4px;">
		<hr class="mt-0">
	</div>  
	

	<!-- ******************* OUTPUT SECTION **************************-->

	<div class="container pt-50 pb-30" id="Outpout">

    <%= form_with(model: quote_form, local: true) do |form| %>
  <% if quote_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote_form.errors.count, "error") %> prohibited this quote_form from being saved:</h2>

      <ul>
      <% quote_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



		<div class="row">
			<div class="col-md-4 col-xs-12" id="elevator-amount">
				<%= form.label :Elevators, style:"font-size: 18px;" %>
                <%= form.text_field :Elevators, class:".col-6 .col-md-4", id:"el-req" %>
			</div>
		
			<div class="col-md-4 col-xs-12" id="elevator-unit-price">
				<%= form.label :Price_Per_Unit, style:"font-size: 18px;" %>
                <%= form.text_field :Price_Per_Unit, class:".col-6 .col-md-4", id:"e-u-p" %>
			</div> 
		</div>

		<div class="row">
			<div id="elevator-total-price" class="col-md-4 col-xs-12">
				<%= form.label :Sum_For_All_Units, style:"font-size: 18px;" %>
                <%= form.text_field :Sum_For_All_Units, class:".col-6 .col-md-4", id:"e-t-p" %>	
			</div> 
		
			<div id="installation-fees" class="col-md-4 col-xs-12">
				<%= form.label :Installation_Fees, style:"font-size: 18px;" %>
                <%= form.text_field :Installation_Fees, class:".col-6 .col-md-4", id:"inst-fees" %>
			</div>

			<div id="final-price" class="col-md-4 col-xs-12">
				<%= form.label :Total_Price, style:"font-size: 18px;" %>
                <%= form.text_field :Total_Price, class:".col-6 .col-md-4", id:"fin-price" %>
			</div>
		</div>

	</div>
   

	<div class="row mt-10" style="background-image:-webkit-linear-gradient(left,#9e040a,white,#3072e0);height: 4px;">
		<hr class="mt-0">
	</div>  

	 
	<div class="container pt-50 pb-30" id="Info">

		<div class="container pt-50 pb-30" id="Info">
			<div class="row align-items-start">
				<div class="field">
					<%= form.label :FirstName, style:"font-size: 18px;" %>
					<%= form.text_field :FirstName , class:".col-6 .col-md-4"  %>
				</div>
			</div>
			<div class="row align-items-start">
				<div class="field">
					<%= form.label :LastName, style:"font-size: 18px;" %>
					<%= form.text_field :LastName , class:".col-6 .col-md-4"  %>
				</div>
			</div>
			<div class="row align-items-start">
				<div class="field">
					<%= form.label :PhoneNumber, style:"font-size: 18px;" %>
					<%= form.text_field :PhoneNumber , class:".col-6 .col-md-4"  %>
				</div>
			</div>
			<div class="row align-items-start">
			<div class="field">
					<%= form.label :Email, style:"font-size: 18px;" %>
					<%= form.text_field :Email, class:".col-6 .col-md-4" %>
				</div>
			</div>
			<div class="row align-items-start">
				<div class="actions">
					<%= form.submit class:"btn btn-danger btn-md" , style:"font-size: 18px;" %>
				</div>
			</div>
				
			</div>


      <!--  <%= render 'form', quote_form: @quote_form %>

        <%= link_to 'Back', quote_forms_path %>

	-->
	
	</div>
	
	 <% end %>


	<div class="row" style="background-image:-webkit-linear-gradient(left,#3072e0,#9e040a,white);height: 8px;">
		<hr class="mt-0">
	</div>
</div>

app/views/quote_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @quote_form.FirstName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @quote_form.LastName %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @quote_form.PhoneNumber %>
</p>

<p>
  <strong>Email:</strong>
  <%= @quote_form.Email %>
</p>
<p>
  <strong>Elevators:</strong>
  <%= @quote_form.Elevators %>
</p>
<p>
  <strong>Price Per Unit:</strong>
  <%= @quote_form.Price_Per_Unit %>
</p>
<p>
  <strong>Sum For All Units:</strong>
  <%= @quote_form.Sum_For_All_Units %>
</p>
<p>
  <strong>Installation Fees:</strong>
  <%= @quote_form.Installation_Fees %>
</p>
<p>
  <strong>Total Price:</strong>
  <%= @quote_form.Total_Price%>
</p>

<%= link_to 'Edit', edit_quote_form_path(@quote_form) %> |
<%= link_to 'Back', quote_forms_path %>